### ISSUE TITLE
how to use tf-text on mac m2 ? 

### ISSUE THREAD

**Issue by aino-debasish** [sun1638650145/Libraries-and-Extensions-for-TensorFlow-for-Apple-Silicon#17]
Hi, 

I am trying to use tf-text on Mac M2. Not clear if your repo provides the wheel or only tutorial. pip3 install tf-text / tf_text results in no matching distribution. 

TIA

**Comment by sun1638650145** [comment]
@aino-gautam First, this repository provides tutorials. Additionally, to save time, you can directly download pre-compiled  `whl` from the [releases page](https://github.com/sun1638650145/Libraries-and-Extensions-for-TensorFlow-for-Apple-Silicon/releases). As for why you couldn't find a match, it's because the official distribution doesn't provide ARM `whl`.

**Comment by aino-debasish** [comment]
Thanks for your kind response. Do you think it's feasible to build a wheel for ARM / M2 from source? My skills in CPP are not terrible 😊 or is the limitation because of metal lib from Apple?

**Comment by sun1638650145** [comment]
I'm not entirely sure what you mean, but if you're referring to building `tensorflow-text` from source, there is a tutorial available for that. The official releases are only provided for `x86-64` macOS and Linux, similar to how `Raspberry Pi` support is community-maintained.

**Comment by sun1638650145** [comment]
@aino-gautam Due to your prolonged lack of response to this issue, I will now close this issue.
