### ISSUE TITLE
Is there a way to run object detection api on Macos 12

### ISSUE THREAD

**Issue by preyawnshoe** [sun1638650145/Libraries-and-Extensions-for-TensorFlow-for-Apple-Silicon#3]

**Comment by sun1638650145** [comment]
Please describe in detail, are you referring to `tensorflow-io` support?

**Comment by kumarpriyanshu2k2** [comment]
yes, I am not able to run object detection API due to unsupported TensorFlow io, probably because the wheel is for macos 11

❯ python3 -m pip install --no-deps dist/tensorflow_io-0.24.0-cp39-cp39-macosx_11_0_arm64.whl
DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
WARNING: Requirement 'dist/tensorflow_io-0.24.0-cp39-cp39-macosx_11_0_arm64.whl' looks like a filename, but the file does not exist
Processing ./dist/tensorflow_io-0.24.0-cp39-cp39-macosx_11_0_arm64.whl
ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory: '/Users/priyanshukumar/io/dist/tensorflow_io-0.24.0-cp39-cp39-macosx_11_0_arm64.whl'

**Comment by preyawnshoe** [comment]
yes, I am not able to install tensorflow io in my conda environment
![Screenshot 2022-05-23 at 4 37 19 PM](https://user-images.githubusercontent.com/93030904/169806313-c3d7e1f6-bad1-4dd7-8912-33d700651e47.jpg)

❯ python3 -m pip install --no-deps dist/tensorflow_io-0.26.0-cp39-cp39-macosx_11_0_arm64.whl
ERROR: tensorflow_io-0.26.0-cp39-cp39-macosx_11_0_arm64.whl is not a supported wheel on this platform.

**Comment by sun1638650145** [comment]
This approach works with the Object Detection API, but the support is not perfect. For this reason, I haven't written a `tensorflow-io` tutorial.

1. Use `virtualenv` to create an environment (please do not use `conda` to create new environments!).

   ````python
   python3 -m venv ~/tensorflow-macos
   source ~/tensorflow-macos/bin/activate
   ````

2. Install `hdf5` (please do not use `conda` pre-compiled `hdf5`!).

   ````python
   brew install hdf5
   export CPATH="/opt/homebrew/include/"
   export HDF5_DIR="/opt/homebrew/"
   ````

3. Install the `tensorflow-macos` and `tensorflow-metal` plugins.

   ````python
   pip install tensorflow-macos==2.9.0
   pip install tensorflow-metal==0.5.0
   ````

4. Download and extract `io 0.26.0`.

   ````python
   wget https://github.com/tensorflow/io/archive/refs/tags/v0.26.0.zip
   unzip v0.26.0.zip
   cd io-0.26.0
   ````

5. Build `io`.

   ````python
   python setup.py -q bdist_wheel --project tensorflow_io_gcs_filesystem
   python setup.py -q bdist_wheel
   ````

6. Install the `whl` file (please install the `tensorflow_io_gcs_filesystem` first, and use the `--no-deps` parameter).

   ````python
   pip install --no-deps ./dist/tensorflow_io_gcs_filesystem-0.25.0-cp39-cp39-macosx_12_0_arm64.whl
   pip install --no-deps ./dist/tensorflow_io-0.25.0-cp39-cp39-macosx_12_0_arm64.whl
   ````

**Comment by preyawnshoe** [comment]
It worked (with a warning) Thank you so much.

**Comment by sun1638650145** [comment]
I won't close this issue since `io` can not be built perfectly yet. If you still need it, you can continue to follow it, and I will close it when I can build it perfectly.

**Comment by sun1638650145** [comment]
@kumarpriyanshu2k2 Now, `io` can be built perfectly on Apple silicon. You can find a tutorial [here](https://github.com/sun1638650145/Libraries-and-Extensions-for-TensorFlow-for-Apple-Silicon/blob/main/tutorials/io/io.md) or directly download the [whl](https://github.com/sun1638650145/Libraries-and-Extensions-for-TensorFlow-for-Apple-Silicon/releases/tag/v2.13) file.
